name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cc: [g++-8, clang++-9]
        type: [Debug, Release]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cc }}
      - name: install/upgrade pip
        run: python -m pip install --upgrade pip
      - name: install conan
        run: pip install conan
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_CXX_COMPILER=${CC} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        env:
          CC: ${{ matrix.cc }}
          BUILD_TYPE: ${{ matrix.type }}
      - name: build
        run: cmake --build build
      - name: bench
        run: cd build && ./bin/bench
